# To Calculate three variable arithmatic Operators
a = int(input("Enter the Value for a : "))
b = int(input("Enter the Value for b : "))
c = int(input("Enter the value for c : "))
print(a," + ",b," = ",a+b)
print(a," - ",b," = ",a-b)
print(a," * ",b," = ",a*b)
print(a," / ",b," = ",a/b)
print(a," // ",b," = ",a//b)
print(a," ** ",c,"  = ",a**c)
print(a," + ",b,"* ",c," = ",a+b*c)
print("(",a," + ",b," ) ","* ",c," = ",(a+b)*c)
print(a," ** ",c,"  + ",b," = ",a**c+b)
print(a,"+",b,"//",c," = ",a+b//c)
print("(",a,"+",b,")","//",c," = ",(a+b)//c)
